name: Install Helm and Deploy to AWS EKS

on:
  push:
    branches:
      - feature/deployment  # Trigger only on the deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out the repository

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change this to your AWS region

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version  # Verify Helm installation

      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Authenticate with Amazon EKS
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name my-eks-cluster
          kubectl cluster-info  # Verify connection

      - name: Deploy Nginx Using Helm
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo update
          helm install my-nginx stable/nginx --namespace default

      - name: Verify Deployment
        run: |
          kubectl get pods -n default
          kubectl get svc -n default
